Controllers/DriverController.cs
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Drawing.Printing;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimplifiedDMV.Data;
using SimplifiedDMV.Helper;
using SimplifiedDMV.Models;
using SimplifiedDMV.Models.ViewModels;

namespace SimplifiedDMV.Controllers
{
    public class DriverController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DriverController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string searchText = "", int pageNumber = 1)
        {
            IQueryable<Driver> objDriverList;
            string FirstNameToSearch = searchText.Trim();
            if (FirstNameToSearch != "" && FirstNameToSearch != null)
            {
                objDriverList = from driver in _db.Drivers
                                where driver.FirstName.Contains(FirstNameToSearch)
                                                select driver;
            }
            else
                objDriverList = _db.Drivers;
            if (objDriverList != null)
            {
                objDriverList.OrderBy(driver => driver.Id);
                return View(await PaginatedList<Driver>.CreateAsync(objDriverList, pageNumber, 8));
            }
            else
                return View(new PaginatedList<Vehicle>(null, 0, pageNumber, 8));

        }
        //Get
        public IActionResult Create()
        {
            var statesList = States.GetAll();
            var driverViewModel = new DriverViewModel();
            driverViewModel.StatesSelectList = new List<SelectListItem>();
            foreach(var state in statesList)
            {
                driverViewModel.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
            }

            return View(driverViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DriverViewModel obj)
        {
            if (ModelState.IsValid)
            {
                Driver driverToCreate = obj.DriverModel;
                _db.Drivers.Add(driverToCreate);
                _db.SaveChanges();
                TempData["success"] = "Driver created sucessfully!";
                return RedirectToAction("Index");
            }
            else
            {
                var statesList = States.GetAll();
                obj.StatesSelectList = new List<SelectListItem>();
                foreach (var state in statesList)
                {
                    obj.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
                }
                TempData["error"] = "Driver creation failed!";
                return View(obj);
            }
        }
        //GET
        public async Task<IActionResult> Detail(int id, int pageNumber = 1)
        {
            var vehiclesViewModel = new VehiclesViewModel();
            vehiclesViewModel.DriverId = id;
            IQueryable<Vehicle> objVehicleList;
            //Driver driverForDetails = _db.Drivers.Include(driv => driv.Vehicles).Single(driv => driv.Id == id);
            //objVehicleList = driverForDetails.Vehicles;
            objVehicleList = _db.Vehicles.Include(c => c.Driver).Where(c => c.DriverId == id);
            if (objVehicleList != null)
            {
                vehiclesViewModel.VehiclesToDisplay = await PaginatedList<Vehicle>.CreateAsync(objVehicleList.AsQueryable(), pageNumber, 8);
            }
            else
                vehiclesViewModel.VehiclesToDisplay = new PaginatedList<Vehicle>(null, 0, pageNumber, 8);
            return View(vehiclesViewModel);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            var statesList = States.GetAll();
            var driverViewModel = new DriverViewModel();
            var DriverFromDb = _db.Drivers.Find(id);
            driverViewModel.StatesSelectList = new List<SelectListItem>();
            driverViewModel.DriverModel = DriverFromDb;
            foreach (var state in statesList)
            {
                driverViewModel.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
            }
            return View(driverViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DriverViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.Drivers.Update(obj.DriverModel);
                _db.SaveChanges();
                TempData["success"] = "Driver is Updated sucessfully!";
                return RedirectToAction("Index");
            }
            else
            {
                var statesList = States.GetAll();
                obj.StatesSelectList = new List<SelectListItem>();
                foreach (var state in statesList)
                {
                    obj.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
                }
                TempData["error"] = "Driver creation failed!";
                return View(obj);
            }
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DriverFromDb = _db.Drivers.Find(id);
            if (DriverFromDb == null)
            {
                return NotFound();
            }

            return View(DriverFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var DriverToDelete = _db.Drivers.Find(id);
            if (DriverToDelete == null)
            {
                return NotFound();
            }
            _db.Drivers.Remove(DriverToDelete);
            _db.SaveChanges();
            TempData["success"] = "Driver deleted sucessfully!";
            return RedirectToAction("Index");
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimplifiedDMV</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimplifiedDMV.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">Driver</a>
                        </li>
                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex" asp-action="Index">
                        <input class="form-control me-sm-2" type="text" name="searchText" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">
                            Search
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SimplifiedDMV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}