Models/Driver.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace SimplifiedDMV.Models
{
    public class Driver
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("First Name")]
        [StringLength(20)]
        public string FirstName { get; set; }
        [Required]
        [DisplayName("Last Name")]
        [StringLength(20)]
        public string LastName { get; set; }
        [Required]
        [DisplayName("Phone number")]
        [Phone]
        public string PhoneNumber { get; set; }
        [Required]
        [StringLength(100)]
        public string Address { get; set; }
        [Required]
        [StringLength(30)]
        public string State { get; set; }
        [DisplayName("Zip code")]
        [MaxLength(8)]
        public string ZipCode { get; set; }
        [DisplayName("Register date")]
        public DateTime RegisteredDateTime { get; set; } = DateTime.Now;

        public IList<Vehicle>? Vehicles { get; set; }
    }
}

Models/ViewModels/DriverViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using SimplifiedDMV.Models.DomainModels;

namespace SimplifiedDMV.Models.ViewModels
{
    public class DriverViewModel
    {
        public List<SelectListItem>? StatesSelectList { get; set; }

        public Driver DriverModel { get; set; }
    }
}

Controllers/DriverController.cs
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Drawing.Printing;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimplifiedDMV.Data;
using SimplifiedDMV.Helper;
using SimplifiedDMV.Models;
using SimplifiedDMV.Models.ViewModels;

namespace SimplifiedDMV.Controllers
{
    public class DriverController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DriverController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(string searchText = "", int pageNumber = 1)
        {
            IQueryable<Driver> objDriverList;
            string FirstNameToSearch = searchText.Trim();
            if (FirstNameToSearch != "" && FirstNameToSearch != null)
            {
                objDriverList = from driver in _db.Drivers
                                where driver.FirstName.Contains(FirstNameToSearch)
                                                select driver;
            }
            else
                objDriverList = _db.Drivers;
            if (objDriverList != null)
            {
                objDriverList.OrderBy(driver => driver.Id);
                return View(await PaginatedList<Driver>.CreateAsync(objDriverList, pageNumber, 8));
            }
            else
                return View(new PaginatedList<Vehicle>(null, 0, pageNumber, 8));

        }
        //Get
        public IActionResult Create()
        {
            var statesList = States.GetAll();
            var driverViewModel = new DriverViewModel();
            driverViewModel.StatesSelectList = new List<SelectListItem>();
            foreach(var state in statesList)
            {
                driverViewModel.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
            }

            return View(driverViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DriverViewModel obj)
        {
            if (ModelState.IsValid)
            {
                Driver driverToCreate = obj.DriverModel;
                _db.Drivers.Add(driverToCreate);
                _db.SaveChanges();
                TempData["success"] = "Driver created sucessfully!";
                return RedirectToAction("Index");
            }
            else
            {
                var statesList = States.GetAll();
                obj.StatesSelectList = new List<SelectListItem>();
                foreach (var state in statesList)
                {
                    obj.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
                }
                TempData["error"] = "Driver creation failed!";
                return View(obj);
            }
        }
        //GET
        public async Task<IActionResult> Detail(int id, int pageNumber = 1)
        {
            var vehiclesViewModel = new VehiclesViewModel();
            vehiclesViewModel.DriverId = id;
            IQueryable<Vehicle> objVehicleList;
            //Driver driverForDetails = _db.Drivers.Include(driv => driv.Vehicles).Single(driv => driv.Id == id);
            //objVehicleList = driverForDetails.Vehicles;
            objVehicleList = _db.Vehicles.Include(c => c.Driver).Where(c => c.DriverId == id);
            if (objVehicleList != null)
            {
                vehiclesViewModel.VehiclesToDisplay = await PaginatedList<Vehicle>.CreateAsync(objVehicleList.AsQueryable(), pageNumber, 8);
            }
            else
                vehiclesViewModel.VehiclesToDisplay = new PaginatedList<Vehicle>(null, 0, pageNumber, 8);
            return View(vehiclesViewModel);
        }
        //GET
        public IActionResult Edit(int? id)
        {
            var statesList = States.GetAll();
            var driverViewModel = new DriverViewModel();
            var DriverFromDb = _db.Drivers.Find(id);
            driverViewModel.StatesSelectList = new List<SelectListItem>();
            driverViewModel.DriverModel = DriverFromDb;
            foreach (var state in statesList)
            {
                driverViewModel.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
            }
            return View(driverViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DriverViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.Drivers.Update(obj.DriverModel);
                _db.SaveChanges();
                TempData["success"] = "Driver is Updated sucessfully!";
                return RedirectToAction("Index");
            }
            else
            {
                var statesList = States.GetAll();
                obj.StatesSelectList = new List<SelectListItem>();
                foreach (var state in statesList)
                {
                    obj.StatesSelectList.Add(new SelectListItem { Text = state.Name, Value = state.Id });
                }
                TempData["error"] = "Driver creation failed!";
                return View(obj);
            }
        }
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DriverFromDb = _db.Drivers.Find(id);
            if (DriverFromDb == null)
            {
                return NotFound();
            }

            return View(DriverFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var DriverToDelete = _db.Drivers.Find(id);
            if (DriverToDelete == null)
            {
                return NotFound();
            }
            _db.Drivers.Remove(DriverToDelete);
            _db.SaveChanges();
            TempData["success"] = "Driver deleted sucessfully!";
            return RedirectToAction("Index");
        }
        
    }
}

Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimplifiedDMV.Helper;
using SimplifiedDMV.Models.ViewModels;
using SimplifiedDMV.Models;
using SimplifiedDMV.Data;

namespace SimplifiedDMV.Controllers
{
    public class VehicleController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VehicleController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Create(int id)
        {

            var typeList = Types.GetAll();
            var brandList = Brands.GetAll();
            var yearList = Years.GetAll();
            Vehicle vehicleModel = new Vehicle();
            vehicleModel.DriverId = id;

            var registerVehicleViewModel = new RegisterVehicleViewModel();

            registerVehicleViewModel.TypesSelectList = new List<SelectListItem>();
            registerVehicleViewModel.BrandsSelectList = new List<SelectListItem>();
            registerVehicleViewModel.YearsSelectList = new List<SelectListItem>();
            registerVehicleViewModel.DriverId = id;
            registerVehicleViewModel.VehicleModel= vehicleModel;

            foreach (var type in typeList)
            {
                registerVehicleViewModel.TypesSelectList.Add(new SelectListItem { Text = type.Name, Value = type.Name });
            }
            foreach (var brand in brandList)
            {
                registerVehicleViewModel.BrandsSelectList.Add(new SelectListItem { Text = brand.Name, Value = brand.Name });
            }
            foreach (var year in yearList)
            {
                registerVehicleViewModel.YearsSelectList.Add(new SelectListItem { Text = year.Name, Value = year.Name });
            }

            return View(registerVehicleViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RegisterVehicleViewModel obj)
        {
            int dirverId = obj.DriverId;
            try { 
                _db.Vehicles.Add(obj.VehicleModel);
                _db.SaveChanges();
                TempData["success"] = "Vehicle registered sucessfully!";
                return RedirectToAction("Detail", "Driver", new {id = dirverId});
            }
            catch(Exception ex) 
            {
                var typeList = Types.GetAll();
                var brandList = Brands.GetAll();
                var yearList = Years.GetAll();


                obj.TypesSelectList = new List<SelectListItem>();
                obj.BrandsSelectList = new List<SelectListItem>();
                obj.YearsSelectList = new List<SelectListItem>();

                foreach (var type in typeList)
                {
                    obj.TypesSelectList.Add(new SelectListItem { Text = type.Name, Value = type.Name });
                }
                foreach (var brand in brandList)
                {
                    obj.BrandsSelectList.Add(new SelectListItem { Text = brand.Name, Value = brand.Name });
                }
                foreach (var year in yearList)
                {
                    obj.YearsSelectList.Add(new SelectListItem { Text = year.Name, Value = year.Name });
                }
                TempData["error"] = "Vehicle registration failed!";
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(int id)
        {
            var typeList = Types.GetAll();
            var brandList = Brands.GetAll();
            var yearList = Years.GetAll();

            var registerVehicleViewModel = new RegisterVehicleViewModel();

            registerVehicleViewModel.TypesSelectList = new List<SelectListItem>();
            registerVehicleViewModel.BrandsSelectList = new List<SelectListItem>();
            registerVehicleViewModel.YearsSelectList = new List<SelectListItem>();
            registerVehicleViewModel.DriverId = _db.Vehicles.Find(id).DriverId;
            registerVehicleViewModel.VehicleModel = _db.Vehicles.Find(id);
            foreach (var type in typeList)
            {
                registerVehicleViewModel.TypesSelectList.Add(new SelectListItem { Text = type.Name, Value = type.Name });
            }
            foreach (var brand in brandList)
            {
                registerVehicleViewModel.BrandsSelectList.Add(new SelectListItem { Text = brand.Name, Value = brand.Name });
            }
            foreach (var year in yearList)
            {
                registerVehicleViewModel.YearsSelectList.Add(new SelectListItem { Text = year.Name, Value = year.Name });
            }

            return View(registerVehicleViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RegisterVehicleViewModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.Vehicles.Update(obj.VehicleModel);
                _db.SaveChanges();
                TempData["success"] = "Vehicle is Updated sucessfully!";
                return RedirectToAction("Detail", "Driver", new { id = obj.DriverId });
            }
            else
            {
                var typeList = Types.GetAll();
                var brandList = Brands.GetAll();
                var yearList = Years.GetAll();


                obj.TypesSelectList = new List<SelectListItem>();
                obj.BrandsSelectList = new List<SelectListItem>();
                obj.YearsSelectList = new List<SelectListItem>();
 
                foreach (var type in typeList)
                {
                    obj.TypesSelectList.Add(new SelectListItem { Text = type.Name, Value = type.Name });
                }
                foreach (var brand in brandList)
                {
                    obj.BrandsSelectList.Add(new SelectListItem { Text = brand.Name, Value = brand.Name });
                }
                foreach (var year in yearList)
                {
                    obj.YearsSelectList.Add(new SelectListItem { Text = year.Name, Value = year.Name });
                }
                TempData["error"] = "Vehicle update failed!";
                return View(obj);
            }

        }
        //GET
        public IActionResult Delete(int id)
        {
            var registerVehicleViewModel = new RegisterVehicleViewModel();
            registerVehicleViewModel.DriverId = _db.Vehicles.Find(id).DriverId;
            registerVehicleViewModel.VehicleId = _db.Vehicles.Find(id).Id;
            registerVehicleViewModel.VehicleModel = _db.Vehicles.Find(id);

            return View(registerVehicleViewModel);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(RegisterVehicleViewModel obj)
        {
            var VehicleToDelete = _db.Vehicles.Find(obj.VehicleId);
            try
            {
                _db.Vehicles.Remove(VehicleToDelete);
                _db.SaveChanges();
                TempData["success"] = "Vehicle deleted sucessfully!";
            }
            catch (Exception ex)
            {
                TempData["error"] = "Vehicle deleted sucessfully!";
            }
            return RedirectToAction("Detail", "Driver", new { id = obj.DriverId });
        }
    }
}

Views/Driver/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@using SimplifiedDMV.Models
@model SimplifiedDMV.Models.ViewModels.DriverViewModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary ">Register new driver</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="DriverModel.FirstName"></label>
            <input asp-for="DriverModel.FirstName" class="form-control" />
            <span asp-validation-for="DriverModel.FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.LastName"></label>
            <input asp-for="DriverModel.LastName" class="form-control" />
            <span asp-validation-for="DriverModel.LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.PhoneNumber"></label>
            <input asp-for="DriverModel.PhoneNumber" class="form-control" />
            <span asp-validation-for="DriverModel.PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.Address"></label>
            <input asp-for="DriverModel.Address" class="form-control" />
            <span asp-validation-for="DriverModel.Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.State"></label>
            <select asp-items="Model.StatesSelectList" asp-for="DriverModel.State" class="form-select"></select>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.ZipCode"></label>
            <input asp-for="DriverModel.ZipCode" class="form-control" />
            <span asp-validation-for="DriverModel.ZipCode" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Driver" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Driver/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model Driver

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-danger">This Driver is going to be deleted, Are you sure?</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="State"></label>
            <input asp-for="State" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ZipCode"></label>
            <input asp-for="ZipCode" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Driver" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Driver/Detail.cshtml
@model SimplifiedDMV.Models.ViewModels.VehiclesViewModel
@{
    ViewData["Title"] = "Detail";
    int displayOrder = 0;
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Vehicles resgistered under driver with id: @Model.DriverId</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Vehicle" asp-action="Create" asp-route-id="@Model.DriverId" class="btn btn-primary">
                <i class="bi bi-plus"></i> &nbsp; Register New Vehicle
            </a>
        </div>
    </div>
    <br />


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Vehicle Id
                </th>
                <th>
                    Driver's First Name
                </th>
                <th>
                    Driver's Last Name
                </th>
                <th>
                    Driver Id
                </th>
                <th>
                    Vin Number
                </th>
                <th>
                    Type
                </th>
                <th>
                    Brand
                </th>
                <th>
                    Model
                </th>
                <th>
                    Year
                </th>
                <th>
                    Register Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.VehiclesToDisplay)
            {
                displayOrder += 1;

                <tr>
                    <td>
                        @obj.Id
                    </td>
                    <td>
                        @obj.Driver.FirstName
                    </td>
                    <td>
                        @obj.Driver.LastName
                    </td>
                    <td>
                        @obj.Driver.Id
                    </td>
                    <td>
                        @obj.VinNumber
                    </td>
                    <td>
                        @obj.Type
                    </td>
                    <td>
                        @obj.Brand
                    </td>
                    <td>
                        @obj.Model
                    </td>
                    <td>
                        @obj.Year
                    </td>
                    <td>
                        @obj.RegisteredDateTime
                    </td>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-controller="Vehicle" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2 rounded"> <i class="bi bi-pencil-fill"></i> Edit</a>
                            <a asp-controller="Vehicle" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger  mx-2 rounded"> <i class="bi bi-trash"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @{
        var prevDisabled = !Model.VehiclesToDisplay.PreviousPage ? "disabled" : "";
        var nextDisabled = !Model.VehiclesToDisplay.NextPage ? "disabled" : "";
        var next1Disabled = (Model.VehiclesToDisplay.PageIndex + 1 > Model.VehiclesToDisplay.TotalPages) ? "disabled" : "";
        var next2Disabled = (Model.VehiclesToDisplay.PageIndex + 2 > Model.VehiclesToDisplay.TotalPages) ? "disabled" : "";
        var next3Disabled = (Model.VehiclesToDisplay.PageIndex + 3 > Model.VehiclesToDisplay.TotalPages) ? "disabled" : "";
        var next4Disabled = (Model.VehiclesToDisplay.PageIndex + 4 > Model.VehiclesToDisplay.TotalPages) ? "disabled" : "";
    }
    <div>
        <ul class="pagination pagination-lg">
            <li class="page-item @prevDisabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex-1)">&laquo;</a>
            </li>
            <li class="page-item active">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@Model.VehiclesToDisplay.PageIndex">@Model.VehiclesToDisplay.PageIndex</a>
            </li>
            <li class="page-item @next1Disabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex + 1)">@(Model.VehiclesToDisplay.PageIndex + 1)</a>
            </li>
            <li class="page-item @next2Disabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex + 2)">@(Model.VehiclesToDisplay.PageIndex + 2)</a>
            </li>
            <li class="page-item @next3Disabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex + 3)">@(Model.VehiclesToDisplay.PageIndex + 3)</a>
            </li>
            <li class="page-item @next4Disabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex + 4)">@(Model.VehiclesToDisplay.PageIndex + 4)</a>
            </li>
            <li class="page-item @nextDisabled">
                <a class="page-link" asp-action="Detail" asp-route-pageNumber="@(Model.VehiclesToDisplay.PageIndex+1)">&raquo;</a>
            </li>
        </ul>
    </div>


</div>

Views/Driver/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@using SimplifiedDMV.Models
@model SimplifiedDMV.Models.ViewModels.DriverViewModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary ">Edit driver</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <input asp-for="DriverModel.Id" class="form-control" hidden/>
        <div class="mb-3">
            <label asp-for="DriverModel.FirstName"></label>
            <input asp-for="DriverModel.FirstName" class="form-control" />
            <span asp-validation-for="DriverModel.FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.LastName"></label>
            <input asp-for="DriverModel.LastName" class="form-control" />
            <span asp-validation-for="DriverModel.LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.PhoneNumber"></label>
            <input asp-for="DriverModel.PhoneNumber" class="form-control" />
            <span asp-validation-for="DriverModel.PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.Address"></label>
            <input asp-for="DriverModel.Address" class="form-control" />
            <span asp-validation-for="DriverModel.Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.State"></label>
            <select asp-items="Model.StatesSelectList" asp-for="DriverModel.State" class="form-select"></select>
        </div>
        <div class="mb-3">
            <label asp-for="DriverModel.ZipCode"></label>
            <input asp-for="DriverModel.ZipCode" class="form-control" />
            <span asp-validation-for="DriverModel.ZipCode" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Driver" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back
        </a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Driver/Index.cshtml
@model PaginatedList<Driver>
@{
    ViewData["Title"] = "Index";
    int displayOrder = 0;
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Driver List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Driver" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus"></i> &nbsp; Register New Driver
            </a>
        </div>
    </div>
    <br />


    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Driver Id
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Phone Number
                </th>
                <th>
                    Address
                </th>
                <th>
                    State
                </th>
                <th>
                    Zip Code
                </th>
                <th>
                    Register Date
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @obj.Id
                    </td>
                    <td>
                        @obj.FirstName
                    </td>
                    <td>
                        @obj.LastName
                    </td>
                    <td>
                        @obj.PhoneNumber
                    </td>
                    <td>
                        @obj.Address
                    </td>
                    <td>
                        @obj.State
                    </td>
                    <td>
                        @obj.ZipCode
                    </td>
                    <td>
                        @obj.RegisteredDateTime
                    </td>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-controller="Driver" asp-action="Detail" asp-route-id="@obj.Id" class="btn btn-primary  mx-2 rounded"> <i class="bi bi-car-front-fill"></i> Detials</a>
                            <a asp-controller="Driver" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2 rounded"> <i class="bi bi-pencil-fill"></i> Edit</a>
                            <a asp-controller="Driver" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger  mx-2 rounded"> <i class="bi bi-trash"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @{
        var prevDisabled = !Model.PreviousPage ? "disabled" : "";
        var nextDisabled = !Model.NextPage ? "disabled" : "";
        var next1Disabled = (Model.PageIndex + 1 > Model.TotalPages) ? "disabled" : "";
        var next2Disabled = (Model.PageIndex + 2 > Model.TotalPages) ? "disabled" : "";
        var next3Disabled = (Model.PageIndex + 3 > Model.TotalPages) ? "disabled" : "";
        var next4Disabled = (Model.PageIndex + 4 > Model.TotalPages) ? "disabled" : "";
    }
    <div>
        <ul class="pagination pagination-lg">
            <li class="page-item @prevDisabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex-1)">&laquo;</a>
            </li>
            <li class="page-item active">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@Model.PageIndex">@Model.PageIndex</a>
            </li>
            <li class="page-item @next1Disabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)">@(Model.PageIndex + 1)</a>
            </li>
            <li class="page-item @next2Disabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 2)">@(Model.PageIndex + 2)</a>
            </li>
            <li class="page-item @next3Disabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 3)">@(Model.PageIndex + 3)</a>
            </li>
            <li class="page-item @next4Disabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 4)">@(Model.PageIndex + 4)</a>
            </li>
            <li class="page-item @nextDisabled">
                <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex+1)">&raquo;</a>
            </li>
        </ul>
    </div>
    

</div>